# Generated by Django 4.1.7 on 2023-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=32)),
                ("barrio", models.CharField(max_length=200)),
                ("departamento", models.CharField(max_length=200)),
                ("square_meters", models.FloatField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("price", models.IntegerField()),
                ("currency", models.CharField(max_length=16)),
                ("full_link", models.CharField(max_length=200)),
            ],
        ),
    ]
