# Generated by Django 4.1.7 on 2023-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house_price_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="house",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="square_meters",
            field=models.CharField(max_length=32),
        ),
    ]
