# Generated by Django 4.1.7 on 2023-03-20 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("house_price_app", "0002_alter_house_bathrooms_alter_house_bedrooms_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={"managed": False},
        ),
    ]
