# Generated by Django 4.1.7 on 2023-03-22 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("house_price_app", "0003_alter_house_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="house",
            table="house",
        ),
    ]
